name: Python package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"] # Consider if you need to build for all these or just one for publishing
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8 # Or your desired build Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build # Using pypa/build
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build package
        run: |
          python -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-github-packages:
    name: Publish Python distribution to GitHub Packages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      # id-token: write # Not needed for direct twine upload with token
      contents: read   # For checkout, if any step in this job needed it (though build job handles checkout)
      packages: write  # Essential for GITHUB_TOKEN/RELEASE_GITHUB_TOKEN to publish
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.RELEASE_GITHUB_TOKEN }}
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution to GitHub Packages
        run: |
          pip install twine
          python -m twine upload --repository-url https://pypi.pkg.github.com/${{ github.repository_owner }} dist/* --non-interactive
